### PR TITLE
Add support for Anki 2.1.31+

### LINKED ISSUE #34: Encounter Error With Latest Version of Anki
I have disable all other plugins. 
The error popups when I edit a field and loose focus of that field.
```
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-27 19:05:39
Add-ons possibly involved: ⁨Edit Field During Review Cloze⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-10>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File ~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "~/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt/editor.py", line 421, in mungeHTML
  File "aqt/gui_hooks.py", line 1606, in __call__
  File "aqt/editor.py", line 1219, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'
```

### LINKED ISSUE #36: Error in Anki 2.1.33 causing serious image issues
I'm getting an error whenever I try to use this for the first time on Anki 2.1.33 (I never noticed it on earlier versions).  It then causes any images that have spaces in their filename to get renamed and consistently causes the problem until I restart Anki. 

For example `img class="resizer" src="help (2).png" style="width: 1262px;"` becomes `img class="resizer" src="help%252520%2525282%252529.png" style="width: 1262px;"` and I can't edit it even with by going into the HTML editor with ctrl+shift+x

**Error message:**
```
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-16 18:35:54
Add-ons possibly involved: ⁨Edit Field During Review Cloze, popup_dictionary⁩

Caught exception:

Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-152>", line 2, in linkHandler_wrapper
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/popup_dictionary/main.py", line 216, in linkHandler
    return _old(self, url)
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-86>", line 2, in linkHandler_wrapper
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 193, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 153, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt/editor.py", line 421, in mungeHTML
  File "aqt/gui_hooks.py", line 1606, in __call__
  File "aqt/editor.py", line 1217, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'
```

### PR DESCRIPTION
**Pull request by hikaru-y**
Hello,

Due to the commits ankitects/anki@4720645, ankitects/anki@f5479ed and ankitects/anki@f5479ed, an `AttributeError` is raised on Anki 2.1.31 or higher. This PR should fix the issue.

Fixes #34, Fixes #36

### CODE REVIEW

**Comment by p4nix** [comment]
It should also be possible to just set Editor.mw = mw and then just use Editor instead of None, or is that bad practice?

    else:
        # aqt.editor.Editor.onBridgeCmd
        Editor.mw = mw
        txt = unicodedata.normalize("NFC", val)
        txt = Editor.mungeHTML(Editor, txt)
        txt = txt.replace("\x00", "")
        txt = mw.col.media.escapeImages(txt, unescape=True)
        field = note[fld]

**Comment by havewisdom** [comment]
@p4nix thank you. it works better

**Comment by AnKingMed** [comment]
As we haven't heard from @BlueGreenMagick in a while, I compiled this into a .ankiaddon file people can download. I tested it briefly and it looks like it will override the current version without affecting any future updates.

[link](https://drive.google.com/file/d/1JfvXKl5XPGo0_eBEaXc18pWEbaz37Oog/view?usp=sharing)

**Comment by hugomarins** [comment]
@AnKingMed , even using your compiled version, Im still facing the image name serious issue you mentioned.

Was the problem solved for you?

https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/issues/36#issue-703526855

**Comment by AnKingMed** [comment]
@hugomarins I updated to 2.1.26beta1 and it seems to have resolved it for me. See if that works for you. I'd be curious because I haven't found a reason exactly why

**Comment by hugomarins** [comment]
@AnKingMed did you mean 2.1.36beta1? If this is the case, I tried, but still have problems (by the way, I use Windows version). Thanks anyway!

**Comment by AnKingMed** [comment]
Yes. That’s odd. Are you getting the error message?   Try deleting your version and then installing my compiled version and again and restart. 

Also know that this does not fix images that have already been changed. You have to manually change the image name back (which sucks..)

**Comment by hugomarins** [comment]
@AnKingMed Sadly, this is still not working. No error messages, just that behavior of changing file names, being impossible to alter back the name in the edit html window until Anki is restarted.

**Comment by AnKingMed** [comment]
hmm.. that's interesting. It stops happening if you disable this add-on correct?  And still occurs if this is the only add-on installed?   Unfortunately, @BlueGreenMagick hasn't responded for a while so I'm not 100% sure how to look into it, but describing the problem as best as possible will help them find the issue.  We might be able to ping @Arthur-Milchior as he has spent time with this add-on's code

**Comment by hikaru-y** [comment]
@hugomarins I was able to reproduce the issue, and have just pushed a new commit to fix the issue. Could you try the commit efdaf76 to see if the issue is fixed?

@AnKingMed This PR has not been merged yet, so if you plan to create a new `.ankiaddon` file and distribute it, maybe you might want to append something like "unofficial fixed version" to the addon name, as follows:

    {
        "conflicts": [
            "1020366288",
            "385888438"
        ],
        "name": "Edit Field During Review (Cloze) [unofficial fixed version]",
        "package": "edit-field-during-review-cloze-unofficial-fixed-version"
    }

**Comment by hugomarins** [comment]
@hikaru-y I got the following error when using the proposed change:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.36 (53a984ba) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-10 13:32:45

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 562, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-62>", line 2, in _linkHandler
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 199, in myLinkHandler
    saveThenRefreshFld(reviewer, note, fld, new_val)
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 159, in saveThenRefreshFld
    saveField(note, fld, new_val)
  File "C:\Users\hugom\AppData\Roaming\Anki2\addons21\385888438\reviewer.py", line 135, in saveField
    txt = Editor.mungeHTML(None, txt)
  File "aqt\editor.py", line 423, in mungeHTML
  File "aqt\gui_hooks.py", line 1606, in __call__
  File "aqt\editor.py", line 1225, in reverse_url_quoting
AttributeError: 'NoneType' object has no attribute 'mw'

Below my Debug info:

    
    Anki 2.1.36 (53a984ba) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-11-10 13:32:45
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['customize_editor_stylesheet-fork by ijgnd', 0, 'None', mod]
    Add Hyperlink ['318752047', 2020-07-29T17:37, 'None', '']
    Add Table ['1237621971', 2020-07-25T09:19, 'None', mod]
    Advanced Browser ['874215009', 2020-11-08T08:03, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-09-24T08:01, 'None', '']
    Anki Simulator ['817108664', 2020-07-21T11:17, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', mod]
    Answer Confirmation for 21 ['1354051622', 2019-09-24T08:34, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-10-20T07:40, 'None', '']
    Batch Editing ['291119185', 2019-09-24T07:39, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2020-09-01T05:58, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-09-24T08:34, 'None', '']
    Custom Styles font color background colour classes ['1899278645', 2020-09-20T09:23, 'None', '']
    Deck name in title 21 ['699175524', 2019-09-24T08:37, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-06-11T09:32, 'None', mod]
    Editor Autocomplete for Anki 21 ['925419294', 2020-10-06T18:51, 'None', '']
    Enhance main window ['877182321', 2020-09-02T18:49, 'None', mod]
    Export cards selected in the Browser ['1983204951', 2020-02-03T13:31, 'None', '']
    External Editor ['16727059', 2020-07-27T06:06, 'None', mod]
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T00:10, 'None', '']
    Flag label ['671965183', 2020-05-14T08:05, 'None', mod]
    Highlight Search Results in the Browser ['225180905', 2019-09-24T07:45, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Keep model of add cards ['424778276', 2020-05-16T20:18, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2020-07-11T20:06, 'None', '']
    Large and Colorful Buttons ['1829090218', 2019-11-16T22:31, 'None', '']
    Mini Format Pack ['295889520', 2019-09-24T07:40, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-03-31T17:19, 'None', '']
    More Overview Stats 21 ['738807903', 2019-09-24T08:22, 'None', '']
    Multiple Choice for Anki ['1566095810', 2020-09-02T06:32, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-15T21:59, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-09-24T08:33, 'None', '']
    Pretzel Logic Retention Benchmarking ['1168065472', 2020-04-25T00:13, 'None', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T03:26, 'None', '']
    Quizlet to Anki 21 Importer with audio support ['1362209126', 2020-09-10T14:28, 'None', '']
    ReMemorize Rescheduler with sibling and logging v140 ['323586997', 2020-04-17T04:07, 'None', mod]
    Remove card history ['2089200096', 2018-04-23T03:50, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T13:17, 'None', '']
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T17:13, 'None', '']
    Show fields source html in editor ['1574324795', 2020-03-28T04:08, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T06:11, 'None', '']
    Spell Checker ['spell_checker', 0, 'None', '']
    Symbols As You Type ['2040501954', 2020-04-30T11:32, 'None', '']
    Symbols ['1461102936', 2019-09-24T08:35, 'None', mod]
    Syntax Highlighting for Code ['1463041493', 2018-10-06T22:31, 'None', '']
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T16:43, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2020-05-08T10:16, 'None', '']
    deck and card info sidebar during review ['673114053', 2020-09-20T09:17, 'None', mod]
    export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2020-09-20T08:50, 'None', '']
    extended editor for field for tables searchreplace  ['805891399', 2020-07-29T19:54, 'None', mod]
    scheduler Reduce Interval growth for very mature cards ['9512376', 2020-08-08T11:33, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1168065472 1237621971 1354051622 1362209126 1374772155 1461102936 1463041493 153625306 1556734708 1566095810 1574324795 16727059 1807206748 1829090218 1898445115 1899278645 1967530655 1983204951 2040501954 2084557901 2089200096 225180905 266436365 291119185 295889520 300884351 318752047 323586997 354407385 385888438 424778276 538879081 561945101 671965183 673114053 699175524 738807903 805891399 814349176 817108664 861263371 874215009 877182321 925419294 9512376
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['rememorize_btn', 0, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2020-06-09T08:54, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2020-09-02T01:53, 'None', mod]
    Edit Field During Review ['1020366288', 2020-10-07T09:22, 'None', '']
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T14:42, 'None', '']
    PDF Glossary Exporter ['pdf_glossary', 2019-08-19T09:35, 'None', '']
    Quick Colour Changing ['2491935955', 2019-09-24T08:35, 'None', mod]
    Show LaTeX and MathJax result in editorbrowser ['882784122', 2020-05-18T20:48, 'None', '']
    text editor for Latex the selection or html source FORK ['1184418999', 2020-07-25T20:13, 'None', mod]

Thanks

**Comment by hikaru-y** [comment]
@hugomarins Thanks for the feedback! Maybe you have not applied the fix correctly. Can you try one of the following:  
- Go to efdaf76 > click on the 3 dots icon on the right side > click on "View file" > click on the <kbd>Raw</kbd> button > copy the entire text > replace the code of the original `reviewer.py` with the text you copied  
- or
- `git clone -b add-support-for-2-1-31+ https://github.com/hikaru-y/Edit-Field-During-Review-Cloze.git`, then replace the original `reviewer.py` with the downloaded `reviewer.py`.

**Comment by hugomarins** [comment]
Sorry @hikaru-y , my mistake; I'm not used to coding or using Github. I did what you said and it worked perfectly! You did a miracle! As far as I could see, the image names are being preserved and I detected no abnormal behavior. I'll let you know if I see something. Thanks so much for sharing your achievements. This add-on was very helpful, and I've tried everything I could and have found no solution. Now it is solved. God bless you!

**Comment by AnKingMed** [comment]
@hikaru-y I had formatted the manifest so that it would update their current version of edit field during review but will still allow for updates via anki web so that users don't get confused. Would you advise against that?

**Comment by hikaru-y** [comment]
@AnKingMed That makes sense. In that case, I would probably just append "unofficial fixed version" or something similar to the value of `name` key, and set "385888438" to `package` key as you have already done.
